/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-20 14:07:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class StudentRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"StudentServlet\" method=\"post\">\r\n");
      out.write("<fieldSet >\r\n");
      out.write("<legend>Student Registration</legend>\r\n");
      out.write("<div>\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th align=\"left\">\r\n");
      out.write("<lable for=\"studentname\">StudentName</lable>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<td>:\r\n");
      out.write("<input type=\"text\" name=\"studentName\" placeholder=\"@manojreddy\" required autocomplete=\"off\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<th align=\"left\">\r\n");
      out.write("<lable for=\"cname\" align=\"left\">CollegetName</lable></th>\r\n");
      out.write("<td>:\r\n");
      out.write("<input type=\"text\" name=\"collegeName\" placeholder=\"@mallaReddyCollege\" required>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<th align=\"left\">\r\n");
      out.write("<lable for=\"passoutYear\">PassoutYear</lable>\r\n");
      out.write("</th>\r\n");
      out.write("<td>:\r\n");
      out.write("<select id=\"passoutYear\" name=\"passoutYear\">\r\n");
      out.write("<option value=\"select\" selected>select</option>\r\n");
      out.write("<option value=\"2018\">2018</option>\r\n");
      out.write("<option value=\"2019\">2019</option>\r\n");
      out.write("<option value=\"2020\">2020</option>\r\n");
      out.write("<option value=\"2021\">2021</option>\r\n");
      out.write("<option value=\"2022\">2022</option>\r\n");
      out.write("<option value=\"2023\">2023</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("<lable for=\"qualification\" >qualification</lable>\r\n");
      out.write("</th>\r\n");
      out.write("<td>:\r\n");
      out.write("<select id =\"qualification\" name=\"qualification\" >\r\n");
      out.write("<option value=\"select\" selected>select</option>\r\n");
      out.write("<optgroup lable=\"Btech\">\r\n");
      out.write("<option value =\"EEE\">EEE</option>\r\n");
      out.write("<option value =\"ECE\">ECE</option>\r\n");
      out.write("<option value =\"CSE\">CSE</option>\r\n");
      out.write("<option value =\"CIVIL\">CIVIL</option>\r\n");
      out.write("<option value =\"MECH\">MECH</option>\r\n");
      out.write("<option value =\"OTHERS\">OTHERS</option></optgroup>\r\n");
      out.write("<optgroup lable=\"degree\">\r\n");
      out.write("<option value =\"BSC\">BSC</option>\r\n");
      out.write("<option value =\"MPCS\">MPCS</option>\r\n");
      out.write("<option value =\"BCOM\">BCOM</option>\r\n");
      out.write("<option value =\"BA\">BA</option>\r\n");
      out.write("<option value =\"CS\">CS</option>\r\n");
      out.write("<option value =\"OTHERS\">OTHERS</option>\r\n");
      out.write("</optgroup>\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th align=\"left\">\r\n");
      out.write("<lable for=\"courses\">Courses:</lable></th>\r\n");
      out.write("<td>:\r\n");
      out.write("<select id =\"courses\" name=\"courses\">\r\n");
      out.write("<option value=\"select\" selected>select</option>\r\n");
      out.write("<option value=\"JAVAFULLSTACK\">JAVAFULLSTACK </option>\r\n");
      out.write("<option value=\"PYTHONFULLSTACK\">PYTHONFULLSTACK </option>\r\n");
      out.write("<option value=\"JAVA\">JAVA</option>\r\n");
      out.write("<option value=\"HTML/CSS\">HTML/CSS </option>\r\n");
      out.write("<option value=\"ANGULAR/REACT\">ANGULAR/REACT </option>\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"submit\" value=\"submit\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</fieldSet>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
